### ISSUE TITLE
Scrolling isn't working for me at all (Chrome 36.0.1985.125 – not Canary)

### ISSUE THREAD

**Issue by jacklenox** [philc/vimium#1117]
I've been using Vimium for just over a week and I'm really enjoying using it. However the scroll functions just don't seem to work at all on any website. Any ideas?

**Comment by benregn** [comment]
j/k works and doesn't work for me...

I'm using: 

- OS X 10.10.1
- Vimium 1.49

Chrome:

- 42.0.2292.0 canary (64-bit)
    - Scrolling Hacker news works fine
    - All other pages work fine
- 40.0.2214.94 (64-bit)
    - Scrolling Hacker news works fine
    - No other pages work

**Comment by smblott-github** [comment]
@benregn.  Can you give a specific URL that doesn't work?  Works [here](https://news.ycombinator.com/), for me.

**Comment by smblott-github** [comment]
This might be related to this strange glitch I just fixed: 90d2addc9b8f95f9272f8c2a77bdaf9dfebc0fa8.

**Comment by smblott-github** [comment]
@benregn.  Could you try the following, please?
- Go to a page where scrolling doesn't work.
- Scroll down a bit with the mouse or with the arrow keys.
- Press and hold `k`.  Or tap `k` many times.

Do you notice anything odd?  Does it scroll *very slowly* up?

**Comment by benregn** [comment]
@smblott-github news.ycombinator.com (as noted) is so far the only page I know that j/k works on, pretty much any other page it doesn't work. E.g. http://en.wikipedia.org or http://medium.com.

I tried following the steps you suggest but no luck.

**Comment by smblott-github** [comment]
@benregn.

Desperate measures...  Would you mind creating a new (clean) Chrome profile, installing Vimium from the Chrome Store and trying it that way?  That would rule out anything in your configuration, and any interference from other extensions.

**Comment by benregn** [comment]
@smblott-github just did that and still no luck.  When I tried Canary I had all my usual extensions installed.

**Comment by scottstanfield** [comment]
Just seeing this thread...I will try to reproduce as well and report back. 

---
Scott Stanfield
scott@vertigo.com

**Comment by jtreminio** [comment]
Scrolling hasn't worked for me in quite some time.

It works on HN, but doesn't work on this page (this issues page). Reddit won't scroll, in fact almost no other page but HN will scroll.

**Comment by mrmr1993** [comment]
Do you have any flags set in `chrome://flags`?

**Comment by jtreminio** [comment]
Hot damn, that fixed it @mrmr1993 

I've been running Chromium for over a year and a half now because Vimium wouldn't work. I even uninstalled/reinstalled Chrome but I guess some settings carried over.

Resetting all flags to default and restarting Chrome seems to have fixed the issue completely!

**Comment by benregn** [comment]
@mrmr1993 @scottstanfield I also reset my flags - fixed it.  I started turning them on one by one and it stopped working after I enabled the Experimental JavaScript flag (chrome://flags/#enable-javascript-harmony).

**Comment by scottstanfield** [comment]
Oh wow. It's 5am here. I'm tempted to get up and try it. But will probably just play more Trivia Crack. Will check in a few hours!

---
Scott Stanfield
scott@vertigo.com

**Comment by scottstanfield** [comment]
**It works!** 

All I did was disable a single flag:
chrome://flags/#enable-experimental-web-platform-features

My test page is "Designer News" instead of "Hacker News":
https://tdc.switchboardhq.com/

j/k now work for scrolling. I haven't checked everything yet, but looking good.

**Comment by smblott-github** [comment]
Confirm, for me (Debian, Chrome 40.0.2214.111), enabling

```
chrome://flags/#enable-experimental-web-platform-features
```

breaks scrolling in 1.45, 1.49 and `master`.  I'm not seeing console errors, so it'll require further investigation.

This flag was also on @benregn's list.

(Well done @mrmr1993.)

**Comment by scottstanfield** [comment]
Yep, working great now. I don't remember when I flipped that flag on, but I did at some point. Thanks all! This has made me very happy.

**Comment by nabn** [comment]
Resetting the flags worked for me too. Thanks.

**Comment by marlun** [comment]
Has there been any development on this? I'm on Mac with Chrome 47.0.2498.0 canary (64-bit) when I enable chrome://flags/#enable-experimental-web-platform-features scrolling stops working.

**Comment by clessg** [comment]
Same problem on my end.

**Comment by smblott-github** [comment]
Scrolling seems to work (with that flag enabled) for me -- but I'm on Linux.

@marlun, @clessg are there any console messages which suggest what might be failing?

**Comment by marlun** [comment]
There's an error icon next to the Stylish extension in settings and if you click on it and choose view in developer tools you get:

```
/**
 * Retrieve the enabled status for the given URL.
 * @param {String} url URL of the requested object.
 * @return {Boolean} The enabled status for the given URL.
 */
Styles.prototype.isEnabled = function(url) {
  if (this.styles[url] === undefined) {
    return false;
  }
  return this.styles[url][this.ENABLED_PROPERTY];
};
```

where the return statements is marked with red background. Also if I view the console the following log is in it:

```
Error in event handler for extension.onRequest: TypeError: Cannot read property '_enabled' of null
    at Styles.isEnabled (chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/styles.js:106:26)
    at Styles.getCombinedRulesForPage (chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/styles.js:291:17)
    at chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/listeners.js:43:35
Error in event handler for extension.onRequest: TypeError: Cannot read property 'id' of undefined
    at Styles.getCombinedRulesForIframe (chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/styles.js:327:39)
    at chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/listeners.js:58:35
Error in event handler for extension.onRequest: TypeError: Cannot read property '_enabled' of null
    at Styles.isEnabled (chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/styles.js:106:26)
    at Styles.getCombinedRulesForPage (chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/styles.js:291:17)
    at chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/listeners.js:43:35
Error in event handler for extension.onRequest: TypeError: Cannot read property '_enabled' of null
    at Styles.isEnabled (chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/styles.js:106:26)
    at Styles.getCombinedRulesForPage (chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/styles.js:291:17)
    at Styles.getCombinedRulesForIframe (chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/styles.js:328:38)
    at chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/listeners.js:58:35
Error in event handler for extension.onRequest: TypeError: Cannot read property '_enabled' of null
    at Styles.isEnabled (chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/styles.js:106:26)
    at Styles.getCombinedRulesForPage (chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/styles.js:291:17)
    at chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/listeners.js:43:35
Error in event handler for extension.onRequest: TypeError: Cannot read property 'id' of undefined
    at Styles.getCombinedRulesForIframe (chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/styles.js:327:39)
    at chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/listeners.js:58:35
Error in event handler for extension.onRequest: TypeError: Cannot read property '_enabled' of null
    at Styles.isEnabled (chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/styles.js:106:26)
    at Styles.getCombinedRulesForPage (chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/styles.js:291:17)
    at chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/listeners.js:43:35
```

**Comment by marlun** [comment]
Sorry about the last mail/comment, mixed up two different issues in different projects. I removed the comment again.

**Comment by marlun** [comment]
I checked with this issue in mind this time and the console has the following:

```
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object.registerFrame (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/background_scripts/main.js:873:46)
    at chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/background_scripts/main.js:133:56
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object.registerFrame (chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/background_scripts/main.js:873:46)
    at chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/background_scripts/main.js:133:56
checking keyQueue: [ j ]
new KeyQueue: 
checking keyQueue: [ k ]
new KeyQueue: 
```

**Comment by smblott-github** [comment]
Well, that's interesting, @marlun.  Would you be able to check the front-end console too, please?

(The error you post isn't good, but shouldn't really -- I think -- affect scrolling.)

**Comment by marlun** [comment]
The front-end console has 0 entries.

**Comment by smblott-github** [comment]
OK, @marlun.  Thanks.  I'm starting to get an idea.

- Does the Vomnibar (`o`) work?
- Does find (`/`) work?
- Do link hints (`f`) work?

(I want the answers Yes, No, No.  Otherwise it's back to the drawing board.)

**Comment by marlun** [comment]
They all work.

**Comment by mrmr1993** [comment]
I would be surprised if this isn't related to [Chromium issue 157855](https://code.google.com/p/chromium/issues/detail?id=157855).  Do you have the same issues with chrome://flags/#scroll-top-left-interop (and all other flags at their defaults)?

**Comment by marlun** [comment]
@mrmr1993 Correct, if I reset to the default and enable chrome://flags/#scroll-top-left-interop the scrolling stops working, if I set it to "Default" it starts working again. @smblott-github

**Comment by rajeevksahu** [comment]
Either you have to shift within Bangalore or close by location; we are always prepared to help you with best packaging movers. We deal with all your requisites and help you in all possible ways. We deal with everything from initial stage to final deployment of items.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
We check everything carefully that items are packed, packed or unloaded as per specifications or not. If there is a unique request from client, packaging and movers always respect your priorities. The expert alternatives assure that items are handled with appropriate care and it is transported to the new position without even only one the begining.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
The time that you are wasting in packaging or moving your lengthy items can be invested in other meaningful factors like shopping, see your loved ones, explore the present place and many other factors. The best aspect is that packaging and movers are truly affordable and quickly comes in your price range. The packages can also be personalized based on your needs and specifications.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
So choosing experts for best packaging and movers is not a wrong concept. They will handle your all valuables either it is large or light in weight. They will neat all the factors, it will be packed properly, packed to truck and it will be unloaded to new position immediately.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by ijse** [comment]
I reset all flags and it works again.

Thanks all.
