### ISSUE TITLE
LinkHints.activateModeToOpenInNewForegroundTab opens new tab in the background

### ISSUE THREAD

**Issue by marcelpaulo** [philc/vimium#1522]
When `LinkHints.activateModeToOpenInNewForegroundTab` is remapped to `F`, it opens new tabs in the background and doesn't switch to them. If I remap it to anything else, such as `gf`, for instance, it works as expected, opening new tabs in the foreground.

These screenshots show that my remapping was done and recognized by vimium:

![vimium options - google chrome_002](https://cloud.githubusercontent.com/assets/10074769/6547973/3a205446-c5c8-11e4-8639-87335e1065ad.jpg)

![vimium options - google chrome_003](https://cloud.githubusercontent.com/assets/10074769/6547975/433b2e66-c5c8-11e4-90a3-7c5e42684672.jpg)

Restarting Google Chrome didn't make any difference.

I'm using Vimium version 1.49, Google Chrome 41.0.2272.74 beta (64-bit), Xubuntu 14.10

PS: What a fabulous extension vimium is ! I can't live without it anymore.

**Comment by marcelpaulo** [comment]
Not sure if this is relevant, but I have installed extension `Tab Activate`:

![extensions - google chrome_001](https://cloud.githubusercontent.com/assets/10074769/6548009/7874f16a-c5c9-11e4-8ae7-73a0203547e7.jpg)

**Comment by smblott-github** [comment]
That's pretty weird.  Do you get the same inconsistent behaviour with "Tab Activate" disabled?  Or with a mapping to another capital letter (such as `S`)?

**Comment by marcelpaulo** [comment]
Hey, thanks for the speed-lightning feedback, Stephen ! I could have exhausted these tests before bothering you, please forgive me.

Well, it can get weirder: with `Tab Activate` disabled, I can map any letter, upper or lowercase, but ... with `Tab Activate` enabled, all capital letters don't work, and any lowercase letter (or combination of lowercase letters) works. So, `Tab Activate` somehow is interfering, for sure.

By any chance have you come across or heard of any other extension like `Tab Activate` (it just opens new tabs on the foreground), but which doesn't mess with Vimium ? I'd be happy to switch over.

**Comment by smblott-github** [comment]
Hmm. So it might be something to do with the shift key.  I checked the behaviour in 1.49 (and `master`), and we're passing through both the `keydown` event and the `keyup` event, which is correct.  I'm guessing "Tab Activate" could be doing something with those events.  Short of not using "Tab Activate", I'm not sure what to do...

**Comment by marcelpaulo** [comment]
Thanks a bunch for following up so close on this, Stephen. I've just posted the problem on [`Tab Activate`'s page](http://goo.gl/xp5gDy) on Chrome's Web Store, let's see what the developer says. I'll post any results back here, for reference. For now, I'll leave `Tab Activate` enabled and remap `LinkHints.activateModeToOpenInNewForegroundTab` to `gf`. Once again, thanks a lot !

**Comment by smblott-github** [comment]
@marcelpaulo.  Sorry.  Rewind a bit.  I was wrong previously (still too sleepy).  This *is* a Vimium issue.  What's happening is that we're passing through the `keydown` event for `Shift`, but suppressing the corresponding `keyup` event.  So "Tab Activate" thinks the shift key is still down, and is changing its behaviour accordingly... which is reasonable.  Let me think about this a bit...

**Comment by smblott-github** [comment]
Sorry for misleading you initially, @marcelpaulo.  This is fixed in #1524, now.

**Comment by marcelpaulo** [comment]
I'm the one who should apologize, @smblott-github, for not having dug deeper into your comment. And now I'm the one to thank you for not letting this go and push it through to a solution. I'll follow [these instructions](https://github.com/philc/vimium/blob/master/CONTRIBUTING.md) now, to install Vimium from source. Once again, thanks a bunch !

**Comment by marcelpaulo** [comment]
My lack of knowledge of JavaScript is almost perfect :-( 

I cloned the repo:

    git clone https://github.com/philc/vimium

but got stuck trying to build vimium:

```
paulo@monk:~/src/vimium$ cake.coffeescript build
Error: In /home/paulo/src/vimium/background_scripts/exclusions.coffee, Parse error on line 13: Unexpected 'INDENT'
    at Object.parseError (/usr/lib/coffee-script/lib/coffee-script/parser.js:477:11)
    at Object.parse (/usr/lib/coffee-script/lib/coffee-script/parser.js:554:22)
    at Object.exports.compile.compile (/usr/lib/coffee-script/lib/coffee-script/coffee-script.js:47:20)
    at compileScript (/usr/lib/coffee-script/lib/coffee-script/command.js:182:33)
    at /usr/lib/coffee-script/lib/coffee-script/command.js:152:18
    at fs.js:268:14
    at Object.oncomplete (fs.js:107:15)
```

As you can glaringly see, I'm also fairly ignorant about git-based development.

I'm running Xubuntu 14.10, and installed `coffeescript` from the repositories.

**Comment by smblott-github** [comment]
Can't see what's wrong there (except the build command is usually just `cake build`).  Link to pre-built extension sent by email.

**Comment by marcelpaulo** [comment]
Thanks for your mercy on my ignorance of git and JavaScript development :-) I googled around and saw complaints that the Ubuntu packaging for Node.js and coffeescript is not all that up to date.

Unfortunately, still the same behavior: remapping `LinkHints.activateModeToOpenInNewForegroundTab` to an uppercase letter makes it behave like `LinkHints.activateModeToOpenInNewTab`, remapping lowercase letters works. If I disable `Tab Activate`, both upper and lowercase work.

Just in case, I also tried removing the Chrome Store Vimium, but same results.

Thanks again for your speed-lightning actions !

**Comment by marcelpaulo** [comment]
You nailed it, Steve ! Uppercase letters working with `LinkHints.activateModeToOpenInNewForegroundTab` ! I just noticed now that you don't even have to reload the current tabs after changing vimium config.

Thank you so much for your patience and insistence in seeing this through. Apologies if I perchance insisted, considering that there was a workaround.

**Comment by smblott-github** [comment]
> I just noticed now that you don't even have to reload the current tabs after changing vimium config.

You can thank @mrmr1993 for that (#1041, #1521).

**Comment by marcelpaulo** [comment]
The vimium team is razor sharp, I can see. After this fruitful interchange
with you, I'll make it a point using vimium more extensively, to honor your
team fine work!

Em seg, 9 de mar de 2015 08:31, Stephen Blott <notifications@github.com>
escreveu:
