### ISSUE TITLE
yf not working

### ISSUE THREAD

**Issue by seanw2020** [philc/vimium#4158]
**Describe the bug**
I think this is related(?) to https://github.com/philc/vimium/issues/4147

**To Reproduce**
0. update your chrome and vimium to the latest version
1. Go to https://google.com
2. Press yf
3. Press (whatever key corresponds to a link)
4. Paste in the address bar
5. observe the clipboard has not changed

Include a screenshot if applicable.

**Browser and Vimium version**

Vimium 1.67.2
Chrome Version 106.0.5249.119 (Official Build) (64-bit)

I can reproduce this on BOTH Mac and Windows.

**Comment by gdh1995** [comment]
Yes and this should have been fixed by https://github.com/philc/vimium/commit/dd7302ec0145ef1d73ce825de1d36588c2a3fa3f , so please wait for v1.67.3 being published on Chrome Web Store.

**Comment by AndrewSouthpaw** [comment]
Amazing, thanks the work here! I didn't fully appreciate how often I `yy` or `yf` until it started breaking 😅

**Comment by seanw2020** [comment]
Yeah, me too. I am literally checking every day on the Chrome Web Store, hoping it's been released.

**Comment by tinglycraniumplacidly** [comment]
It still does not work for me with 1.67.3. (loaded via unpacked extension).

**Comment by kenny-evitt** [comment]
If this issue covers `yf` not working at all then I think this can be closed.

Issue #4170 seems to cover a *new* issue with `yf` that might be related to either the original issue fixed in the latest/recent version or some new issue.

**Comment by seanw2020** [comment]
For this issue, I just tried 1.67.3 without using the Chrome Store (wow, the publish time there is VERY slow -- over 10 days!?), on both Windows and Mac, and the issue goes away, so AFAIK, this issue (4158) is just a duplicate.

Thanks everyone!

**Comment by tinglycraniumplacidly** [comment]
Problem didn't go away for me. I'm on Ubuntu 22.10

**Comment by philc** [comment]
I believe this has been fixed; I can't repro today. Please open a new issue if you're still having issues.
