### ISSUE TITLE
Can't click github popups

### ISSUE THREAD

**Issue by Enzodtz** [philc/vimium#4408]
**Describe the bug**

The f shortcut (and probably the other clickable ones), doesn't work on github popups. For example, if you want to approve a pull request you could click on "Review Changes" but not on the buttons that this first one opens.

<img width="646" alt="image" src="https://github.com/philc/vimium/assets/7780770/f89b3552-db4f-43bf-b2db-d0630186c0e8">

**To Reproduce**

1. Go to URL '...'

Include a screenshot if applicable.

**Browser and Vimium version**

Chrome: 120.0.6099.234 (Official Build) (arm64) 
Vimium: 2.0.5

**Comment by gdh1995** [comment]
Duplicate of #4369

**Comment by keithamus** [comment]
Hey friends, I've deployed a fix on GitHub.com, this should no longer be an issue.

**Comment by Enzodtz** [comment]
@keithamus that sounds awesome, thank you. Unfortunately though that is not working for me yet, despite someone in the other thread saying that it worked for them 🤔

**Comment by philc** [comment]
It appears this is not a duplicate of #4369. That issue reported that clicking a Vimium link hint for the "Review changes" button did nothing. This is now fixed (thank you @keithamus!).

Instead, this issue is reporting that link hints do not show for the content inside the Review Changes popup once it's opened. This is not yet resolved. I looked into it briefly and the link hints *do* appear, but they appear *under* the popup. I didn't look further into how this is possible. Vimium's link hints should have the max z-index.

I detected this by hiding the code review popup. In the screenshot below, you can see the link hints are present if you set the popover to 0.5 opacity.

<img width="716" alt="image" src="https://github.com/philc/vimium/assets/8598/acd24a09-48d3-4fb8-ab8f-58276e8423cf">

**Comment by keithamus** [comment]
This will be because popovers are enabled on the browser you’re running (either via `dom.elements.popover.enabled` in `about:config` or by running the 122 beta I think). 

The solution in this case is to make vimiums overlay also use popover.

**Comment by dudicoco** [comment]
@keithamus is that an easy fix? I'm also struggling with this issue.

**Comment by dudicoco** [comment]
thanks @keithamus and @philc!
